spring:
  application:
    name: betapp-config-server
  profiles:
    active: default, development, production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BucketDev/betapp-config-values.git
server:
  port: 8888

